### ISSUE TITLE
Show documentation/help for custom query page

### ISSUE THREAD

**Issue by cejkato2** [CESNET/SecurityCloudGUI#11]
It would be _very_ useful to open manual output / short list of parameters etc in GUI.
Users that don't know fdistdump have to search for help using terminal etc - that's not a user-friendly solution.

**Comment by nerudaj** [comment]
That's a fair point. Also in case of the remote GUI instance, users may not have fdistdump installed on the machines they connect from.
Which form of help do you prefer? Full manpage or excerpt from the manpage regarding output formatting? The list of parameters will probably only be useful to people who know how to work with fdistdump and just don't remember the proper syntax.

**Comment by vaclavbartos** [comment]
(I respond instead of Tomas, we wrote the issue together)

Since user can change/add any parameter in the text-box, not only output formatting, he/she should by able to get help for all parameters. So we think the full manpage would be better (ideally nicely formatted, but as a first step a simple text dump from "man" may suffice).

**Comment by nerudaj** [comment]
Ok, noted.

**Comment by nerudaj** [comment]
For the time being, I've taken the most important part of the fdistdump manpage (excluding some informations related to filesystem and way of storing nfdump files as it's irrelevant for querying.
You can access the fdistdump help by clicking the link directly above the custom options textarea. It opens a modal without affecting the GUI.
