### ISSUE TITLE
Bug in time interval selection

### ISSUE THREAD

**Issue by vaclavbartos** [CESNET/SecurityCloudGUI#12]
In "Graph" page, when I select a time interval and then click on one of the arrows in the bottom right corner, only the "begin" part of timeslot is moved, the "end" part reamins the same. It may result in a state where begin > end (which than obviously causes error when trying to query the database).

Expected behavior is to move the whole interval, i.e. both start and end timestamps.

**Comment by nerudaj** [comment]
It was never intended to move the whole interval, it is supposed to move only start of the interval and select a time slot instead of a window. But if the GUI still remembers the end of the interval, that's a bug. It may not be possible to actually move the interval as the end selector has a specific behaviour, but I'll try to override it.

**Comment by nerudaj** [comment]
Why is expected behaviour to move the whole interval? Are there any usecases for it? From my point of view, any selection is no longer relevant after moving it by any offset somewhere you cannot even see.

**Comment by nerudaj** [comment]
I've fixed the bug. The further modifications to behaviour of graph scrolling are now addressed in issue #17 .
