### ISSUE TITLE
Rewrite cursor class

### ISSUE THREAD

**Issue by nerudaj** [CESNET/SecurityCloudGUI#17]
Rewrite cursor class and subsequently graph scrolling controls in a way nfsen does things. This will require not reset cursor position from updateGraph method. It will also require to scroll the graph relative to cursor (or interval start) rather than graph center.

This issue merges the issue #13 and issue #12 together.

**Comment by vaclavbartos** [comment]
Reply to your question from now-closed issue #12:
> Why is expected behaviour to move the whole interval? Are there any usecases for it? From my point of view, any selection is no longer relevant after moving it by any offset somewhere you cannot even see.

A use case may be for example investigating some periodically occuring event (e.g. it sometimes happen that there is a recurring spike in graph every day at the same time). Or when you're looking at some interval and you're not sure whether some numbers you see are normal or not, so you want to look several days back, what's norm at that time of the day.

I currently rarely use this for longer intervals, I usually work just with a single timeslot, but this is mostly because NfSen automatically computes statistics over the whole interval whenever it's changed, at it takes some (long) time. Since SecurityCloudGUI doesn't do this, so the inteval selection is an immediate operation, and even processing the data in a long interval should be much faster thanks to the paralelization, I'll probably work with intervals much more often.

**Comment by nerudaj** [comment]
Ok, thanks for explanation. I'll work on that.

**Comment by nerudaj** [comment]
@vaclavbartos I've modified the cursor to behave almost exactly as does cursor in nfsen. Could you please test it and verify whether I eliminated all bugs? Thank you

**Comment by vaclavbartos** [comment]
Thanks, now it works as expected. I'm closing the issue.
